apiVersion: v1
kind: Service
metadata:
  name: eventservice
  labels:
    app: eventservice
spec:
  selector:
    app: eventservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5002        #Porta Interna Serviço 
      targetPort: 5002  #Porta Pod